config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create, :index]
    resources :reviews, only: [:new, :create, :index]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true
end


# belongs_to :cocktail
#   belongs_to :ingredient
#   validates :description, presence: true
#   validates :cocktail, uniqueness: { scope: :ingredient }

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :rating, :inclusion => 1..10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :show_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @review = Review.new
    # @ingredients = @cocktail.ingredient
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(select_task)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(select_task)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def show_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def select_task
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def index
    @doses = Dose.all
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(strong_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def strong_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @review = Review.new(strong_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def strong_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/edit.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.association :ingredients %>
  <%= f.submit %>
<% end %>

app/views/cocktails/index.html.erb
<div class="text-center">

<h3 class = "btn btn-info" id = "new-cocktail"> <%= link_to "Create New Cocktail", new_cocktail_path %> </h3>


<div class="container mt-4">
  <h1 class="mb-4 all-cocktails">All Cocktails (<%= @cocktails.length %>)</h1>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-md-4">
      <div class="card mb-4" style="width: 100%;">
        <div class=bg-image></div>
        <div class="card-body">
          <h4 class="card-title"><%= cocktail.name.capitalize %></h4>
          <p class="card-text">This is a description of the yummy cocktail to make you super thirsty</p>
          <%= link_to 'View Cocktail', cocktail_path(cocktail), class: 'card-link btn btn-info' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

</div>

app/views/cocktails/new.html.erb
<div class="container">

<div class="m-3">

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>
</div>
</div>

app/views/cocktails/show.html.erb
<div class="container">

<!-- <div class="d-flex flex-column"> -->


  <h5 class="new-btn"> <%= link_to "Home", cocktails_path %> </h5>
<div class="text-center">
  <div class="inner">
  <h1 class="title m-5"> <%= @cocktail.name %> </h1>
  <h4> <% @cocktail.doses.each do |dose| %> </h4>

  <div class="d-flex justify-content-center">
    <div>
    <div class =card-dose>
      <div>

        <h3 class= "px-3" style="text-decoration: underline;">Dose</h3>
        <h4 class= "px-3"> <%= dose.description %> </h4>

      </div>

      <div>

        <h3 style="text-decoration: underline;">Ingredient</h3>
        <h4 class= "px-3"> <%= dose.ingredient.name %> </h4>

      </div>
    </div>


    <h4 class="new-btn-delete"> <%= link_to "Delete", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
    <h4> <% end %> </h4>


      </div>
      </div>
    </div>
</div>

</div>


<div class="container">
  <div class="card m-5 p-5">
      <h1>What other fans think..</h1>
      <h4> <% @cocktail.reviews.each do |review| %> </h4>
    <div class="review text-center p-3">
      <h4> <%= review.content %> </h4>
      <h4> <%= review.rating %> </h4>
      <h4> <% end %> </h4>
    </div>
    <div class="btn-review m-4">

  <h5 class = "new-btn-dose"> <%= link_to "Add Review", new_cocktail_review_path(@cocktail) %> </h5>

    </div>

  </div>

</div>
  <div class="footer">
    <div class="m-3">
    <h5 class = "new-btn-dose"> <%= link_to "Add Dose", new_cocktail_dose_path(@cocktail) %> </h5>


    </div>
  </div>

app/views/doses/index.html.erb
<h1>Tommy Terrific Doses</h1>


<h3> <% @doses.each do |dose| %> </h3>
<h3> <%= dose.description %> </h3>
<h3> <% end %> </h3>

<h4> <%= link_to "Back to Cocktail", cocktail_path(@cocktail)  %> </h4>

app/views/doses/new.html.erb
<div class="container">

<div class="m-3">

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Yusei+Magic&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed:ital,wght@0,700;1,300;1,900&family=Yusei+Magic&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="text-center my-3">
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0.3) 90%), url(https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80);">
      <div class="container">
        <h1>Tommy's Terrific <strong>Cocktails</strong>!</h1>
        <p>....Not for the faint hearted...</p>
      </div>
    </div>


    </div>

    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">

  <div class="m-3">
    <%= simple_form_for([@cocktail, @review]) do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit %>
    <% end %>


  </div>


</div>